# Generated by Django 5.0.7 on 2024-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_rejecteddemandesretrait_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('nom_agent', models.CharField(max_length=100)),
                ('prenom_agent', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=100)),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('type_de_vue', models.CharField(max_length=100)),
                ('nombre_enfants', models.IntegerField()),
                ('age', models.IntegerField()),
                ('anciennete', models.IntegerField()),
                ('nombre_sejour', models.IntegerField()),
                ('dernier_sejour', models.DateField()),
            ],
        ),
    ]
