# Generated by Django 5.0.7 on 2024-08-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_agentslibre_date_embauche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='user', max_length=128),
        ),
        migrations.AlterField(
            model_name='agentslibre',
            name='dernier_sejour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
