# Generated by Django 5.0.7 on 2024-11-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_agentslibre_date_embauche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('course_manager_email', models.TextField(null=True)),
                ('client_company_name', models.TextField(null=True)),
                ('contract_number', models.TextField(null=True)),
                ('invoice_status', models.TextField(null=True)),
                ('contract_start_date', models.TextField(null=True)),
                ('approval_status', models.TextField(null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('department_code', models.TextField(null=True)),
                ('created_date', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='GainedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'gained_skill',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('hire_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.TextField()),
                ('birth_date', models.TextField(null=True)),
                ('phone_number', models.TextField(null=True)),
                ('salary', models.TextField(null=True)),
                ('professor_number', models.TextField(null=True)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'required_skill',
            },
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='AgentsLibre',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='DemandesTraiter',
        ),
        migrations.DeleteModel(
            name='Historique',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
        migrations.DeleteModel(
            name='RejectedDemandesRetrait',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='listings.department'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
