# Generated by Django 5.0.7 on 2024-11-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_dataset_alter_course_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
